include:
  - board: nice_nano
    shield: corne_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
  - board: nice_nano
    shield: corne_right nice_view_adapter nice_view
  - board: nice_nano
    shield: settings_reset
